### ISSUE TITLE
Bug  Cannot use model,

### ISSUE THREAD

**Issue by chenjun1127** [oriventi/groq-dart-sdk#4]
According to the way the demo is written, use your own api key, Cannot use model appears, and several models have been changed, or so, what is the reason for this, and how to solve it
Frames | Variables | Console
Evaluate expression (Enter) or add a watch (Ctrl+Shift+Enter
request = {Request} GET https://api.groq.com/openai/v1/models/whispeer-large-v3-turbo
 
statusCode=403
ol reasonPhrase = "Forbidden"
of contentLength=4510

**Comment by oriventi** [comment]
Hi, in your url, you wrote whisper with two es. Does this fix your issue?

**Comment by chenjun1127** [comment]
It didn't work, I ran groq_transcribe_example.dart, I just changed it to my own key, Cannot use model appeared, I broke the point debugging and found that there was a 403 error, what is the reason for this?

**Comment by chenjun1127** [comment]
![Uploading 微信截图_20241204144828.png…]()

**Comment by chenjun1127** [comment]
![image](https://github.com/user-attachments/assets/5f548b1f-68d2-40a2-ab16-41a8537ac850)

**Comment by oriventi** [comment]
ok, i tried it. it's working fine now. It seems like groq disabled audio transcriptions, so all requests were forbidden. does it work for you now, too?
