### ISSUE TITLE
Add feature to send a system prompt together with a user prompt at once.

### ISSUE THREAD

**Issue by dayveedaniel** [oriventi/groq-dart-sdk#6]
This feature is necessary when you want to first sent a system instruction / prompt before sending the main prompt, as the documentation says:

> Set an optional system message. This sets the behavior of the assistant and can be used to provide specific instructions for how it should behave throughout the conversation.

The only way to do this now is to first send a message with system role, await. a response then send another message with user role. Most SDKs in other languages already has a feature to send a list of messages.

**Comment by oriventi** [comment]
Hey, you can use `addMessageWithoutSending()`. I implemented this specifically for assistant messages. 
Does this resolve your problem?

**Comment by dayveedaniel** [comment]
Yes it does, thanks a lot. Need to add it to the documentation though
